name: Docker Image CI

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    call_primary_builder:
        permissions:
            contents: read
            id-token: write
            packages: write
        uses: lamusmaser/principal_container_builder_pipeline/.github/workflows/primary_pipeline.yml@main
        with:
            IMAGE_NAME: lamusmaser/video_resolution_detection
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
            GH_USERNAME: ${{ secrets.GH_USERNAME }}
            GH_PAT: ${{ secrets.GH_PAT }}