name: Docker Image CI

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_DH: docker.io
  REGISTRY_GH: ghcr.io
  IMAGE_NAME: lamusmaser/video_resolution_detection

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 # Does not work on ARM, just use the base setup.
        with:
          python-version: '3.8' #Should match the version provided for Docker image.
      - run: pip3 install --upgrade pip wheel
      - run: pip3 install bandit black codespell flake8 flake8-bugbear flake8-comprehensions isort
      - run: black --check --diff --line-length 79 .
      - run: codespell -S ./.git
      - run: flake8 . --count --max-complexity=10 --max-line-length=79 --show-source --statistics
      - run: isort --check-only --line-length 79 --profile black .
      - name: Security Check - Bandit
        run: |
          # Security check using Bandit
          touch security_report.txt
          bandit -r . -o security_report.txt -f 'txt'
          if [ $? -eq 0 ]; then
            echo "Security check passed."
          else
            echo "Security check failed."
            cat security_report.txt
          fi
      - name: Security check report artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Security report
          path: security_report.txt
      - name: Print GitHub Action details
        env:
          EVENT_NAME: ${{ toJSON(github.event_name) }}
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          GH_REF: ${{ toJSON(github.ref) }}
        run: |
          echo $EVENT_NAME
          echo $EVENT_CONTEXT
          echo $GH_REF

  build:
    needs: lint-python
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install/Config Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry (Docker)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_DH }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Log into registry (GitHub)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GH }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push Docker image - build tag
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: lamusmaser/ta_compare_directories:build
          platforms: linux/amd64
          secrets: GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}
 
  build-and-push-main:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v4
    - name: Generate datetag
      id: meta
      run: |
        echo "datetag=$(date +%y.%m.%d)" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install/Config Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry (Docker)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_DH }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Log into registry (GitHub)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GH }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push Docker image - latest tag
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          tags: lamusmaser/ta_compare_directories:${{ steps.meta.outputs.datetag }}, lamusmaser/ta_compare_directories:latest
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          secrets: GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}